name = "ATM10 Sunucu"
author = "ATMTeam"
version = "8.2-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "037d4d8baeb997c8c214d5029020196718028d5252c112d46fe67bdf6cee3c79"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
